### ISSUE TITLE
Move Cognoma to Alex's AWS Account

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/CCDL#2]
Currently Cognoma is deployed within the Greenelab AWS account. As Alex's is footing the bill for this, it makes sense to have it live in that AWS account instead. Cognoma's infrastructure was deployed with Terraform, so moving it should just be a matter of running Terraform with different credentials.

So what we need to do for this is get me set up with permissions for Alex's AWS account, which is already part of the plan.

The other thing is that we need a CognomaDeployer account with permission to write and delete from the S3 bucket that Cognoma is hosted out of.

@Miserlou has agreed to set up these permissions.

**Comment by Miserlou** [comment]
Kurt has credentials now and will create the bucket, I will create the CognomaDeploy IAM permissions once Kurt's TF has created the bucket.

**Comment by kurtwheeler** [comment]
I will get to this some time early next week.
