### ISSUE TITLE
Prepare for 2018 YI Summit

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/CCDL#3]
The 2018 Young Investigators Summit starts on 14 Oct 2018. We'd like to make sure we cover the following broad points:

* refine.bio usability evals
* What can you do with refine.bio? e.g. example notebooks, visualizations
* Graffiti wall(s) (related to: AlexsLemonade/refinebio#512, perhaps others)
* ~Love letter/breakup letter (?)~

We'll use this ticket to track these things. Tagging @dvenprasad @cansav09

**Comment by jaclyn-taroni** [comment]
- [ ] Framing questions for graffiti wall
- [ ] Powerpoint for autoplay that contains the following:
  - [ ] Example visualizations
  - [ ] Screenshots of example notebooks
  - [ ] Some information on MultiPLIER
  - [ ] Adaptation of partner summit slides, e.g., "what can you do with refine.bio"
- [ ] PD flyer

**Comment by dvenprasad** [comment]
Potential question for the graffiti wall: What citation management tools do you use?

**Comment by jaclyn-taroni** [comment]
**Questions for graffiti wall related to AlexsLemonade/refinebio#512**

If you work with RNA-seq data:
1. What form do you like it to be in?
  A. transcript-level counts
  B. transcript-level TPM (transcripts per million)
  C. gene-level counts
  D. gene-level TPM
  E. gene-level count scale data that take library size and transcript length into account

2. What tools do you use for downstream analysis (e.g., clustering, differential expression analysis)?

**Comment by dvenprasad** [comment]
What are your biggest challenges when visualizing data?

**Comment by jaclyn-taroni** [comment]
It would be good to have a heatmap PNG (AlexsLemonade/refinebio#716) for testing for this
